import type { paths } from "@pornarr/api-client";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useState } from "react";
import { useTranslation } from "react-i18next";
import { useSession } from "../../../auth/session";
import { getApiClient } from "../../../lib/api";
import { apiFailure } from "../../../lib/api-error";

type Profiles = paths["/api/filters"]["get"]["responses"][200]["content"]["application/json"];
type Rule = Profiles["personal_rules"][number];
const KEY = ["filters"] as const;
const KINDS = ["term", "tag", "performer", "minimum_confidence", "unknown_performer_age", "unknown_file_type"] as const;
const ACTIONS = ["allow", "quarantine", "reject"] as const;

export function FiltersRoute() {
  const { t } = useTranslation(); const session = useSession(); const cache = useQueryClient();
  const [title, setTitle] = useState(""); const [pattern, setPattern] = useState(""); const [kind, setKind] = useState<(typeof KINDS)[number]>("term"); const [action, setAction] = useState<(typeof ACTIONS)[number]>("reject"); const [result, setResult] = useState<string>();
  const profiles = useQuery({ queryKey: KEY, queryFn: async (): Promise<Profiles> => { const { data, error, response } = await getApiClient().GET("/api/filters"); if (!data || error) throw apiFailure(error, response); return data; } });
  const refresh = (): void => { void cache.invalidateQueries({ queryKey: KEY }); };
  const dryRun = useMutation({ mutationFn: async () => { const { data, error, response } = await getApiClient().POST("/api/filters/dry-run", { body: { title } }); if (!data || error) throw apiFailure(error, response); return data; }, onSuccess: (data) => { const rule = [...(profiles.data?.global_rules ?? []), ...(profiles.data?.personal_rules ?? [])].find((item) => item.id === data.rule_id); setResult(rule ? `${data.action}: ${rule.kind} ${rule.pattern}` : data.action); } });
  const write = useMutation({ mutationFn: async ({ rule, global }: { rule: Rule; global: boolean }) => { const api = getApiClient(); const response = global ? await api.PATCH("/api/filters/global/rules/{rule_id}", { params: { path: { rule_id: rule.id } }, body: { kind: rule.kind, pattern: rule.pattern, action: rule.action, enabled: !rule.enabled } }) : await api.PATCH("/api/filters/rules/{rule_id}", { params: { path: { rule_id: rule.id } }, body: { kind: rule.kind, pattern: rule.pattern, action: rule.action, enabled: !rule.enabled } }); if (response.error) throw apiFailure(response.error, response.response); }, onSuccess: refresh });
  const add = useMutation({ mutationFn: async ({ global }: { global: boolean }) => { const api = getApiClient(); const body = { kind, pattern, action, enabled: true }; const response = global ? await api.POST("/api/filters/global/rules", { body }) : await api.POST("/api/filters/rules", { body: action === "allow" ? { ...body, action: "reject" } : body }); if (response.error) throw apiFailure(response.error, response.response); }, onSuccess: () => { setPattern(""); refresh(); } });
  if (profiles.isPending) return <p>{t("filters.loading")}</p>; if (profiles.isError) return <p role="alert">{t("errors.generic")}</p>;
  const editor = <form onSubmit={(event) => { event.preventDefault(); add.mutate({ global: false }); }}><label htmlFor="filter-kind">{t("filters.kind")}</label><select id="filter-kind" value={kind} onChange={(event) => setKind(event.target.value as (typeof KINDS)[number])}>{KINDS.map((value) => <option key={value} value={value}>{t(`filters.kinds.${value}`)}</option>)}</select><label htmlFor="filter-action">{t("filters.action")}</label><select id="filter-action" value={action} onChange={(event) => setAction(event.target.value as (typeof ACTIONS)[number])}>{ACTIONS.map((value) => <option key={value} value={value}>{t(`filters.actions.${value}`)}</option>)}</select><label htmlFor="filter-pattern">{t("filters.pattern")}</label><input id="filter-pattern" value={pattern} onChange={(event) => setPattern(event.target.value)} required={kind === "term" || kind === "tag" || kind === "performer" || kind === "minimum_confidence"} /><button type="submit">{t("filters.addPersonal")}</button>{session.data?.role === "admin" ? <button type="button" onClick={() => add.mutate({ global: true })}>{t("filters.addGlobal")}</button> : null}</form>;
  return <section><h1>{t("filters.title")}</h1>{editor}<h2>{t("filters.global")}</h2><ul>{profiles.data.global_rules.map((rule) => <li key={rule.id}>{rule.kind}: {rule.pattern} · {rule.action}{session.data?.role === "admin" ? <button type="button" onClick={() => write.mutate({ rule, global: true })}>{rule.enabled ? t("filters.disable") : t("filters.enable")}</button> : null}</li>)}</ul><h2>{t("filters.personal")}</h2><ul>{profiles.data.personal_rules.map((rule) => <li key={rule.id}>{rule.kind}: {rule.pattern} · {rule.action}<button type="button" onClick={() => write.mutate({ rule, global: false })}>{rule.enabled ? t("filters.disable") : t("filters.enable")}</button></li>)}</ul><h2>{t("filters.dryRun")}</h2><form onSubmit={(event) => { event.preventDefault(); dryRun.mutate(); }}><label htmlFor="filter-title">{t("filters.titleField")}</label><input id="filter-title" value={title} onChange={(event) => setTitle(event.target.value)} required /><button type="submit">{t("filters.test")}</button></form>{result ? <p role="status">{result}</p> : null}</section>;
}
