"""Request priorities shared by API, workers and queue estimates."""

ADMIN_REQUEST_PRIORITY = 100
USER_REQUEST_PRIORITY = 80
MONITOR_REQUEST_PRIORITY = 60
RECOMMENDATION_REQUEST_PRIORITY = 40
BACKGROUND_REQUEST_PRIORITY = 20
