/**
 * One title you started and did not finish.
 *
 * Shared by `/continue` and by the row at the top of the library, so the two
 * cannot disagree about what a half-watched title looks like or which device it
 * was left on.
 *
 * The device label is the meta line rather than the studio, because that is the
 * question this tile answers: not "who made it" but "where did I leave it".
 */
import { MediaTile } from "@pornarr/ui";
import type { JSX } from "react";
import { useState } from "react";
import { useTranslation } from "react-i18next";
import { Link } from "react-router-dom";

import { tileBlur, useArtVisible } from "../../lib/art-visibility";
import { formatDuration, progressOf, seedFrom } from "../../lib/format";

export interface ResumeItem {
  readonly media_id: string;
  readonly title?: string | null;
  readonly device_label?: string | null;
  readonly position_seconds: number;
  readonly duration_seconds: number;
}

export function ResumeTile({ item }: { readonly item: ResumeItem }): JSX.Element {
  const { t } = useTranslation();
  const artVisible = useArtVisible();
  // A poster is generated by a background job, so a freshly scanned title has
  // none yet. Handing `MediaTile` an `<img>` that 404s gives it a broken image
  // to draw; `undefined` lets it fall back to the seeded placeholder, which is
  // what the library grid beside this row has always done.
  const [posterFailed, setPosterFailed] = useState(false);
  const title = item.title ?? item.media_id;

  return (
    <MediaTile
      blur={tileBlur(artVisible)}
      title={title}
      meta={item.device_label ?? undefined}
      duration={formatDuration(item.duration_seconds)}
      progress={progressOf(item.position_seconds, item.duration_seconds)}
      seed={seedFrom(item.media_id)}
      poster={
        posterFailed ? undefined : (
          <img
            src={`/api/media/${item.media_id}/poster`}
            alt=""
            loading="lazy"
            onError={() => setPosterFailed(true)}
          />
        )
      }
      action={(content) => (
        // The bare title is not the whole story here: this row's action is not
        // "open" but "pick up where you left off", and a screen reader hearing
        // only the title cannot tell this link apart from the library's.
        <Link
          to={`/library/${item.media_id}`}
          className="block rounded-md"
          aria-label={t("continueWatching.resumeLink", { title })}
        >
          {content}
        </Link>
      )}
    />
  );
}
